name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-dependencies-
      
      - name: Install dependencies
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Run Format
        run: yarn format
